### PR TITLE
Fixes for some sceens + No scrollbars.

### PR DESCRIPTION
**Pull request by RobertARandolph**
No scrollbar didn't allow scrolling with a mouse or keyboard, I fixed that in the variant.

Ive also changed some of the fonts and font sizing so they render correctly on a wide variety of macs. The previous settings did not render correctly on some screens and/or dpi settings.

### CODE REVIEW

**Comment by ptrm** [comment]
Thanks, I will gladly merge the scrolling fix.

When it comes to the font fixes, changing the font-faces isn't acceptable for this style, because, as I see it, this style is 90% the fonts currently used. If you wish to make these changes widely available, I suggest posting a fork on adiumxtras.com.

However, I would be grateful for screenshots of how the style looks on those screens/dpi settings which required fixes. I think it would be possible to provide fixes without changing the font-faces.

**Comment by ptrm** [comment]
To merge the scrollbar fix cleanly, I need you to amend your commit to containt only the scrollbar changes, preferably without the commented code and with tabs instead of spaces as indents.
Otherwise, I can commit the selected changes myself with proper credit if you wish.

**Comment by RobertARandolph** [comment]
Feel free to commit on your own, I'm not very adept with git yet. My apologies for the messed up pull request.

**Comment by ptrm** [comment]
Ok, I will.

As for the screen/dpi issue, I am still hoping to cooperate on it. Please open a new issue and link to some screenshots if you have access to such Macs.

**Pull request closed without merging**
